site_name: JoÃ£o Santos Portfolio

extra_css:
- stylesheets/slider.css
extra_javascript:
- javascripts/slider.js

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: green
      accent: deep purple
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
    - content.code.line_numbers
    - search.suggest
    - search.highlight
  
nav: 
  - ðŸ“¢ Home: index.md
  - ðŸ’¼ Projects:
    - KendirStudios 2025 - Present:
      - About: projects/kendir-studios/about-kendir-studios.md
    - FisipGroup 2023 - 2024:
      - About: projects/fisipgroup/about-fisipgroup.md
      - Mower Mayhem: projects/fisipgroup/mower-mayhem.md  
    - CodeImpact 2023 - 2023:
      - About: projects/codeimpact/about-codeimpact.md
      - Drum Keyboard VR: projects/codeimpact/drum-keyboard.md
      - Drone Strike VR: projects/codeimpact/drone-strike-vr.md
    - Codeverze 2022 - 2024:
      - About: projects/codeverze/about-codeverze.md
      - Store: projects/codeverze/online-store.md
    - Hivolve 2020 - 2022:
      - About: projects/hivolve/about-hivolve.md
      - Adira VR: projects/hivolve/adira-vr.md
      - Empigest: projects/hivolve/empigest.md
      - Essani: projects/hivolve/essani.md
      - Gold Energy: projects/hivolve/gold-energy.md
      - Grandola AR: projects/hivolve/grandola-ar.md
      - Grandola Mupi: projects/hivolve/grandola-mupi.md
      - Grandola VR: projects/hivolve/grandola-vr.md
      - Ooty: projects/hivolve/ooty.md
      - Party Golf: projects/hivolve/party-golf.md
      - Sabseg: projects/hivolve/sabseg.md
      - Siroco: projects/hivolve/siroco.md
      - Superbock: projects/hivolve/superbock.md
      - Valongo 360: projects/hivolve/valongo-360.md
  - ðŸ›’ Asset Store Products:
    - About: asset-store-products/asset-store-products-about.md
    - Script Dependency Viewer: asset-store-products/script-viewer.md
    - WebGL FullScreen Template: asset-store-products/webgl-fullscreen-template.md
  - ðŸŽ® Interactive Portfolio: interactive-portfolio.md